### PR TITLE
filter-pouch is now transform-pouch

### PR DESCRIPTION
**Pull request by nolanlawson**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Also you can avoid exporting `transform` altogether if you use `bind` the `transform` function to the `db` object, but wasn't sure how you feel about `bind` or if you prefer polyfills.

**Comment by calvinmetcalf** [comment]
put it in #5 along with other v2 stuff, I tend to avoid bind as it has some performance issues, so I just used call

**Comment by nolanlawson** [comment]
ah yeah, good call

**Comment by nolanlawson** [comment]
totally unintentional pun ^

**Pull request closed without merging**
