### PR TITLE
options.digest

### PR DESCRIPTION
**Pull request by gr2m**
follow up for https://github.com/calvinmetcalf/crypto-pouch/pull/5#issuecomment-217501486

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
lets just default to sha256 or sha512

**Comment by gr2m** [comment]
I changed it to default to `sha1`, otherwise we would break implementations out there. If we hard code it, then there will be no way for people to use the new version if they rely on decrypting previously encrypted docs

**Comment by calvinmetcalf** [comment]
ok we should probably do a major version bump then and add in the option, (you can migrate by just replicate from a db with the old version to a db with the new version, or to an unencrypted db in the middle to avoid having to versions at the same time).

**Comment by gr2m** [comment]
okay, let’s default to `sha256`. Users can revert to previous behavior by passing `{digest: 'sha1'}` option, sounds good?

**Comment by calvinmetcalf** [comment]
yes

**Comment by gr2m** [comment]
Okay, all set.

**Comment by gr2m** [comment]
can we merge & release?

**Pull request merged**
