### PR TITLE
add option to leave properties unencrypted

### PR DESCRIPTION
**Pull request by gr2m**
this can be used as a workaround for https://github.com/calvinmetcalf/crypto-pouch/issues/13. It's a follow up to https://github.com/calvinmetcalf/crypto-pouch/pull/18

```js
db.crypto('password', {modp: 'modp5', ignore: '_attachments'})
.then(function () {
    return db.put({
      _id: 'id-12345678',
      _attachments: {
        'att.txt': {
          content_type: 'text/plain',
          data: 'TGVnZW5kYXJ5IGhlYXJ0cywgdGVhciB1cyBhbGwgYXBhcnQKTWFrZS' +
                'BvdXIgZW1vdGlvbnMgYmxlZWQsIGNyeWluZyBvdXQgaW4gbmVlZA=='
        }
      }
    });
  })
```

### CODE REVIEW

**Comment by gr2m** [comment]
I’ll clean up commits once I get the go from @calvinmetcalf

**Comment by calvinmetcalf** [comment]
again blocked by nolanlawson/transform-pouch#19

**Comment by gr2m** [comment]
@calvinmetcalf could you explain please?

**Comment by calvinmetcalf** [comment]
I have a major refactor (#26 waiting on that pull)

**Comment by nolanlawson** [comment]
https://github.com/nolanlawson/transform-pouch/pull/19 is fixed now; anything else you need for this PR?

**Comment by gr2m** [comment]
closing in favor of https://github.com/calvinmetcalf/crypto-pouch/pull/29

**Pull request closed without merging**
