### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by calvinmetcalf**
refactors to not asyncly set up encrypting, blocked by ﻿nolanlawson/transform-pouch#19

### CODE REVIEW

**Comment by gr2m** [comment]
﻿nolanlawson/transform-pouch#19 was now merged via https://github.com/nolanlawson/transform-pouch/pull/24

**Comment by gr2m** [comment]
updated it to latest transform-pouch and fixed a few minors in https://github.com/calvinmetcalf/crypto-pouch/pull/28

**Comment by nolanlawson** [comment]
LGTM, except I'm kinda surprised there were so many test cases removed.

**Comment by gr2m** [comment]
Thanks Nolan. I’ll have another look at the tests

**Comment by gr2m** [comment]
@nolanlawson the reason why so many tests were removed is that the 2nd argument `db.crypto(secret, diffieHellman)` was removed, now only `db.crypto(secret)` is supported. I don’t even know what that is :) 

I’ve cleaned up the commits to separate refactoring from the breaking change. I’ll publish it as `2.0.0`

**Comment by nolanlawson** [comment]
Ah I see, so it's a breaking change since part of the API was removed. Looks reasonable, +1.

**Comment by gr2m** [comment]
this was merged via #29

**Pull request closed without merging**
