### PR TITLE
public key and chacha-native

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by gr2m** [comment]
Hey @calvinmetcalf do you still want to switch to `chacha-native`? I don’t know the difference, but I’m happy to help finish things up if you still want to get this merged?

**Comment by calvinmetcalf** [comment]
we already switched to it so this is not neccisary

**Comment by gr2m** [comment]
just to be sure, this PR adds `'sha512'` for the `digest` argument to the `pbkdf2` method which we don’t do in the current code. Is `'sha512'` the default value? I can’t tell from the [crypto docs](https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2sync_password_salt_iterations_keylen_digest)

**Comment by calvinmetcalf** [comment]
default is sha1 so we can add that in a diff pr

**Pull request closed without merging**
